### PR TITLE
Add method for detecting empty spaces

### PR DESCRIPTION
**Pull request by julia-kim**
#6

### CODE REVIEW

**Comment by jlangson** [comment]
I think the empties condition should check for null char '' not '0'. See Nick's comment.

Looks nice!

> Because 0's are generally numbers, and we are using 'X' and 'O' to describe our characters. Changes the 0's to '' -> (empty character) when initializing the array that represents the board.

_Originally posted by @nstoltzfus3 in https://github.com/nstoltzfus3/TicTacToe/issues/3#issuecomment-728846777_

**Comment by julia-kim** [comment]
I did that since the ascii value for null is 0. It worked when I tested it; should I still change it?

**Comment by jlangson** [comment]
I guess it comes down to if we refactor now or later. Would switching to
null char affect how drawBoard is coded?

**Comment by julia-kim** [comment]
It shouldn't! As long as it's still a char array with length 9. alright, I'll just try to refactor it now (not right this moment but for my next pull request)

**Review by nstoltzfus3 — COMMENTED** [review]
Looks good, we get an array of placements where we can place a piece. (i.e. the array length == our total places we can act on.) array length == action space now

**Pull request merged**
